language: java

jdk:
    - oraclejdk8

notifications:
    webhooks:
        urls:
            - secure: "SPXpxdUqqEMqGJK1WbNOo4RxS9Sx2CKvmIUaadwFsSg34qR0KSOhXMnWEo6s+uFLv8OB+Q/nYtWvD9Xg6n+QfgkgmyOLiYsN8cGTG4B8KFKn3Kbl6mfG8IzRP+nQYzXCqcuQ6gf+eurAX3LIvYWF+D2qcHedbZHQfVZ12ai2dTU="
        on_success: always
        on_failure: always
        on_start: false

deploy:
  provider: releases
  api-key: 
    secure: "CJyVgIoL/G0a233WuqPi14eOAk8JlWdErxqbJZYawGmCt5CBJW9l5+4CO4mJqho+EKHmpr+OgGVFq5HV4zQVqVJNFhL86yEucY52v3uQqqT26UmyJwLEtNOpHzVw0pXKvE5LbBOQdl+/8nNhakd6VwGE3qs05F+0ZYyu9LXaal4="
  file: 
      - "target/cardshifter-fx-0.2.jar"
      - "target/cardshifter-server-0.2.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    #must remain on all_branches: true together with tags: true due to the following bug: https://github.com/travis-ci/travis-ci/issues/1675
    #ideal situation would be to change it such that it only builds a release on the master branch on tag push
