language: java

jdk:
    - oraclejdk8

notifications:
    webhooks:
        urls:
            - secure: "vS/3iuMRuwLYMjd8U6z3CUDGbQhjRC0+szQzUDNkeVBz01hzJnQ+OEXLuGoNfS0rKaBIoPW7pmN6Rp3Sn2W2JexrpqvpiUnet5eodZMpiwqOkNjuJPG4qywGed1tnZlpqtAPLgQ9cUvRfkAsVsDwUc+ZtYR7E2IIfDiUMJqLPZo="
        on_success: always
        on_failure: always
        on_start: false        
deploy:
  provider: releases
  api-key: 
    secure: "CJyVgIoL/G0a233WuqPi14eOAk8JlWdErxqbJZYawGmCt5CBJW9l5+4CO4mJqho+EKHmpr+OgGVFq5HV4zQVqVJNFhL86yEucY52v3uQqqT26UmyJwLEtNOpHzVw0pXKvE5LbBOQdl+/8nNhakd6VwGE3qs05F+0ZYyu9LXaal4="
  file: 
      - "target/cardshifter-console-0.1.jar"
      - "target/cardshifter-fx-0.1.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
